2023-05-11 16:21:45,200 - [INFO] - json_server.py[9]: ~~~~~日志开启成功~~~~~
2023-05-11 16:21:45,200 - [INFO] - json_server.py[13]: 获取到了需要处理的文件的名字['/Users/xiechen/Desktop/郑州303/day02/代码/01_josn数据/x01', '/Users/xiechen/Desktop/郑州303/day02/代码/01_josn数据/x00', '/Users/xiechen/Desktop/郑州303/day02/代码/01_josn数据/x02']
2023-05-11 16:21:45,285 - [INFO] - mysql_util.py[29]: 创建链接127.0.0.1:3306//root, 成功!!!
2023-05-11 16:21:45,286 - [INFO] - mysql_util.py[49]: 切换了数据库metadata
2023-05-11 16:21:45,289 - [WARNING] - mysql_util.py[142]: 在metadata已经存在了数据表file_check,故没有进行数据表的创建
2023-05-11 16:29:37,459 - [INFO] - json_server.py[9]: ~~~~~日志开启成功~~~~~
2023-05-11 16:29:37,459 - [INFO] - json_server.py[13]: 获取到了需要处理的文件的名字['/Users/xiechen/Desktop/郑州303/day02/代码/01_josn数据/x01', '/Users/xiechen/Desktop/郑州303/day02/代码/01_josn数据/x00', '/Users/xiechen/Desktop/郑州303/day02/代码/01_josn数据/x02']
2023-05-11 16:29:37,539 - [INFO] - mysql_util.py[29]: 创建链接127.0.0.1:3306//root, 成功!!!
2023-05-11 16:29:37,540 - [INFO] - mysql_util.py[49]: 切换了数据库metadata
2023-05-11 16:29:37,541 - [WARNING] - mysql_util.py[142]: 在metadata已经存在了数据表file_check,故没有进行数据表的创建
2023-05-11 16:30:06,630 - [INFO] - json_server.py[9]: ~~~~~日志开启成功~~~~~
2023-05-11 16:30:06,631 - [INFO] - json_server.py[13]: 获取到了需要处理的文件的名字['/Users/xiechen/Desktop/郑州303/day02/代码/01_josn数据/x01', '/Users/xiechen/Desktop/郑州303/day02/代码/01_josn数据/x00', '/Users/xiechen/Desktop/郑州303/day02/代码/01_josn数据/x02']
2023-05-11 16:30:06,720 - [INFO] - mysql_util.py[29]: 创建链接127.0.0.1:3306//root, 成功!!!
2023-05-11 16:30:06,720 - [INFO] - mysql_util.py[49]: 切换了数据库metadata
2023-05-11 16:30:06,721 - [WARNING] - mysql_util.py[142]: 在metadata已经存在了数据表file_check,故没有进行数据表的创建
2023-05-11 16:31:16,829 - [INFO] - json_server.py[9]: ~~~~~日志开启成功~~~~~
2023-05-11 16:31:16,830 - [INFO] - json_server.py[13]: 获取到了需要处理的文件的名字['/Users/xiechen/Desktop/郑州303/day02/代码/01_josn数据/x01', '/Users/xiechen/Desktop/郑州303/day02/代码/01_josn数据/x00', '/Users/xiechen/Desktop/郑州303/day02/代码/01_josn数据/x02']
2023-05-11 16:31:16,938 - [INFO] - mysql_util.py[29]: 创建链接127.0.0.1:3306//root, 成功!!!
2023-05-11 16:31:16,939 - [INFO] - mysql_util.py[49]: 切换了数据库metadata
2023-05-11 16:31:16,941 - [WARNING] - mysql_util.py[142]: 在metadata已经存在了数据表file_check,故没有进行数据表的创建
